"""Versioned canonical signal flags for unified right-side model research.

The historical z-skill cache is not a point-in-time replay of the live
detectors: several predicates drifted and the cache suppresses repeated hits
for five trading days.  This module freezes one causal research contract:

* the ten z-skill members reproduce the current live detector predicates and
  minimum-history gates for every row;
* no repeated signal is suppressed;
* B2, B3, Vegas, and triple-volume flags retain the columns consumed by the
  current Web selector's family cache.

All calculations operate on one stock at a time.  A row can depend only on the
current and earlier rows after sorting by trade date.
"""

from __future__ import annotations

from collections.abc import Mapping

import numpy as np
import pandas as pd

from quant.features.variable_library import build_continuous_ohlc
from quant.research.right_side_unified_features import (
    compute_right_side_rule_features,
)


CANONICAL_SIGNAL_SCHEMA_VERSION = "right_side_unified_signal_v1_live_z_20260813"

CANONICAL_Z_SIGNALS: tuple[str, ...] = (
    "CHANGAN",
    "PINGHANG",
    "DOUBLE_GUN",
    "GOLDEN_BOWL",
    "BREATHING",
    "KENGQI",
    "ZAIHOU",
    "YUEYUE",
    "KEY_K",
    "VIOLENCE_K",
)

CANONICAL_RIGHT_SIDE_SIGNALS: tuple[str, ...] = (
    "B2",
    "B3",
    "KEY_K",
    "VIOLENCE_K",
    "PINGHANG",
    "DOUBLE_GUN",
    "CHANGAN",
    "KENGQI",
    "VEGAS",
    "TRIPLE_VOLUME_BREAKOUT",
    "GOLDEN_BOWL",
    "ZAIHOU",
    "BREATHING",
    "YUEYUE",
)

B2_FAMILY_SOURCE_COLUMNS: tuple[str, ...] = (
    "b2_any_pchg4_vol15",
    "b2_oversold_pchg3_vol12",
    "b2_bbi_reclaim_vol12",
    "b2_pchg4_vol15",
)
B3_FAMILY_SOURCE_COLUMNS: tuple[str, ...] = (
    "b3_broad_small_pos",
    "b3_broad_calm_pullback",
    "b3_small_pos_amp7",
)
FAMILY_DIRECT_SOURCE_COLUMNS: Mapping[str, str] = {
    "VEGAS": "signal_vegas_tunnel",
    "TRIPLE_VOLUME_BREAKOUT": "signal_tvb_merged",
}

SIGNAL_CONTRACT_NOTES: Mapping[str, str] = {
    "CHANGAN": "src/quant/strategies/custom/z_skill_patterns.py::_detect_changan; live predicate, min_history=12, no cooldown",
    "PINGHANG": "src/quant/strategies/custom/z_skill_patterns.py::_detect_pinghang; live predicate, second cannon on signal day, min_history=12, no cooldown",
    "DOUBLE_GUN": "src/quant/strategies/custom/z_skill_patterns.py::_detect_double_gun; live predicate, signal 1-4 bars after second gun, min_history=18, no cooldown",
    "GOLDEN_BOWL": "src/quant/strategies/custom/z_skill_patterns.py::_detect_golden_bowl; live predicate, min_history=120, no cooldown",
    "BREATHING": "src/quant/strategies/custom/z_skill_patterns.py::_detect_breathing; live 7-bar phase and t-6/t-3 higher-low predicate, min_history=16, no cooldown",
    "KENGQI": "src/quant/strategies/custom/z_skill_patterns.py::_detect_kengqi; live trailing-18 pit-relative window, min_history=25, no cooldown",
    "ZAIHOU": "src/quant/strategies/custom/z_skill_patterns.py::_detect_zaihou; live oldest qualifying anchor in trailing 15 bars, min_history=60, no cooldown",
    "YUEYUE": "src/quant/strategies/custom/z_skill_patterns.py::_detect_yueyue; live inclusive-volume platform predicate, min_history=35, no cooldown",
    "KEY_K": "src/quant/strategies/custom/z_skill_patterns.py::_detect_key_k; live predicate, min_history=20, no cooldown",
    "VIOLENCE_K": "src/quant/strategies/custom/z_skill_patterns.py::_detect_violence_k; live six-prior-body predicate, min_history=20, no cooldown",
    "B2": "Web FAMILY_SIGNAL_COLUMNS OR of B2_ANY/B2_OVERSOLD/B2_BBI/B2_FROM_B1 cache columns",
    "B3": "Web FAMILY_SIGNAL_COLUMNS OR of B3_BROAD_SMALL/B3_BROAD_PULLBACK/B3_SMALL cache columns",
    "VEGAS": "family cache signal_vegas_tunnel generated with OPTIMIZED_VEGAS_TUNNEL_PARAMS",
    "TRIPLE_VOLUME_BREAKOUT": "family cache signal_tvb_merged generated by add_triple_volume_strategy_pool_signals and the production YAML variants",
}


def _parse_dates(values: pd.Series) -> pd.Series:
    text = values.astype(str).str.replace(r"\.0$", "", regex=True)
    compact = text.str.fullmatch(r"\d{8}").fillna(False)
    parsed = pd.to_datetime(values, errors="coerce")
    if compact.any():
        parsed.loc[compact] = pd.to_datetime(
            text.loc[compact],
            format="%Y%m%d",
            errors="coerce",
        )
    return parsed


def _prepare_daily(daily: pd.DataFrame) -> pd.DataFrame:
    if not isinstance(daily, pd.DataFrame):
        raise TypeError("daily must be a pandas DataFrame")
    date_column = "date" if "date" in daily.columns else "trade_date"
    volume_column = "volume" if "volume" in daily.columns else "vol"
    required = (date_column, "open", "high", "low", "close", volume_column)
    missing = [column for column in required if column not in daily.columns]
    if missing:
        raise ValueError(
            "canonical z signals require one-stock date/trade_date and OHLCV; "
            f"missing columns: {missing}"
        )

    out = daily.copy()
    out["date"] = _parse_dates(out[date_column])
    out["volume"] = pd.to_numeric(out[volume_column], errors="coerce")
    for column in ("open", "high", "low", "close", "pre_close"):
        if column in out.columns:
            out[column] = pd.to_numeric(out[column], errors="coerce")
    out = out.dropna(subset=["date", "open", "high", "low", "close", "volume"])
    if out["date"].duplicated().any():
        raise ValueError("canonical z signals require one row per trade date")
    for symbol_column in ("symbol", "ts_code"):
        if symbol_column in out.columns and out[symbol_column].dropna().nunique() > 1:
            raise ValueError("canonical z signals require a single-symbol frame")

    out = out.sort_values("date", kind="stable").reset_index(drop=True)
    price = build_continuous_ohlc(out)
    for column in ("open", "high", "low", "close"):
        out[column] = pd.to_numeric(price[column], errors="coerce")
    out["pre_close"] = out["close"].shift(1)
    return out


def _pinghang_flags(frame: pd.DataFrame, features: pd.DataFrame) -> pd.Series:
    flags = np.zeros(len(frame), dtype=bool)
    strong_yang = features["rs_strong_yang"].fillna(False).to_numpy(dtype=bool)
    volume = frame["volume"].to_numpy(dtype=float)
    open_ = frame["open"].to_numpy(dtype=float)
    close = frame["close"].to_numpy(dtype=float)
    pct = features["rs_pct_chg_1d"].to_numpy(dtype=float)
    kdj_j = features["rs_kdj_j"].to_numpy(dtype=float)

    for position in range(11, len(frame)):
        scan_start = max(0, position - 7)
        events = np.flatnonzero(strong_yang[scan_start : position + 1]) + scan_start
        if len(events) < 2 or int(events[-1]) != position:
            continue
        first, second = int(events[-2]), int(events[-1])
        if second - first - 1 < 2:
            continue
        middle = slice(first + 1, second)
        middle_volume = volume[middle]
        maximum_middle_volume = float(np.nanmax(middle_volume))
        yin_count = int(np.sum(close[middle] <= open_[middle]))
        flags[position] = bool(
            yin_count >= len(middle_volume) * 0.5
            and volume[first] >= maximum_middle_volume * 1.15
            and volume[second] >= maximum_middle_volume * 1.15
            and volume[second] >= volume[first] * 0.9
            and pct[second] >= 4.0
            and kdj_j[second] < 55.0
        )
    return pd.Series(flags, index=frame.index, dtype=bool)


def _double_gun_flags(frame: pd.DataFrame, features: pd.DataFrame) -> pd.Series:
    flags = np.zeros(len(frame), dtype=bool)
    pct = features["rs_pct_chg_1d"].to_numpy(dtype=float)
    is_rise = features["rs_is_rise"].fillna(False).to_numpy(dtype=bool)
    vol_ratio_prev = features["rs_vol_ratio_prev"].to_numpy(dtype=float)
    kdj_j = features["rs_kdj_j"].to_numpy(dtype=float)
    close = frame["close"].to_numpy(dtype=float)
    low = frame["low"].to_numpy(dtype=float)

    def is_gun(position: int) -> bool:
        return bool(
            pct[position] >= 3.0
            and is_rise[position]
            and vol_ratio_prev[position] >= 1.8
        )

    for position in range(17, len(frame)):
        second: int | None = None
        for candidate in range(position - 1, max(0, position - 15), -1):
            if is_gun(candidate):
                second = candidate
                break
        if second is None or position - second > 4:
            continue
        first: int | None = None
        for candidate in range(second - 3, max(0, second - 12), -1):
            if is_gun(candidate):
                first = candidate
                break
        if first is None:
            continue
        middle_ratio = vol_ratio_prev[first + 1 : second]
        average_middle_ratio = float(np.nanmean(middle_ratio))
        flags[position] = bool(
            average_middle_ratio < 1.2
            and kdj_j[second - 1] < 20.0
            and 3 <= second - first <= 10
            and close[position] >= low[second]
        )
    return pd.Series(flags, index=frame.index, dtype=bool)


def _kengqi_flags(frame: pd.DataFrame, features: pd.DataFrame) -> pd.Series:
    flags = np.zeros(len(frame), dtype=bool)
    high = frame["high"].to_numpy(dtype=float)
    low = frame["low"].to_numpy(dtype=float)
    open_ = frame["open"].to_numpy(dtype=float)
    close = frame["close"].to_numpy(dtype=float)
    volume = frame["volume"].to_numpy(dtype=float)
    pct = features["rs_pct_chg_1d"].to_numpy(dtype=float)
    vol_ratio_prev = features["rs_vol_ratio_prev"].to_numpy(dtype=float)

    for position in range(24, len(frame)):
        window_start = position - 17
        relative_low = int(np.nanargmin(low[window_start : position + 1]))
        if relative_low < 5:
            continue
        pit = window_start + relative_low
        pre_slice = slice(pit - 5, pit)
        pre_high = float(np.nanmax(high[pre_slice]))
        pit_low = float(low[pit])
        if not np.isfinite(pre_high) or pre_high <= 0.0 or pre_high <= pit_low:
            continue
        depth = (pre_high - pit_low) / pre_high
        fill = (close[position] - pit_low) / (pre_high - pit_low)
        post_end = min(pit + 5, position) + 1
        post_values = volume[pit + 1 : post_end]
        post_volume = float(np.nanmean(post_values)) if len(post_values) else 0.0
        if not np.isfinite(post_volume):
            post_volume = 0.0
        pre_volume = float(np.nanmean(volume[pre_slice]))
        if not np.isfinite(pre_volume):
            pre_volume = 0.0
        flags[position] = bool(
            depth >= 0.12
            and close[pit] < open_[pit]
            and vol_ratio_prev[pit] >= 1.25
            and 0.78 <= fill <= 1.12
            and post_volume < pre_volume * 0.8
            and pct[position] <= 3.0
        )
    return pd.Series(flags, index=frame.index, dtype=bool)


def _zaihou_flags(frame: pd.DataFrame, features: pd.DataFrame) -> pd.Series:
    flags = np.zeros(len(frame), dtype=bool)
    volume = frame["volume"].to_numpy(dtype=float)
    close = frame["close"].to_numpy(dtype=float)
    pct = features["rs_pct_chg_1d"].to_numpy(dtype=float)
    bbi_distance = features["rs_bbi_distance_pct"].to_numpy(dtype=float)
    bbi_slope = features["rs_bbi_slope_5d_pct"].to_numpy(dtype=float)

    for position in range(59, len(frame)):
        start = position - 14
        anchor: int | None = None
        for candidate in range(start + 5, position):
            prior_mean = float(np.nanmean(volume[candidate - 5 : candidate]))
            if pct[candidate] > 5.0 and volume[candidate] > prior_mean * 1.5:
                anchor = candidate
                break
        if anchor is None:
            continue
        flags[position] = bool(
            bbi_slope[position] > 0.0
            and abs(bbi_distance[position]) < 2.5
            and volume[position] < volume[anchor] * 0.6
        )
    return pd.Series(flags, index=frame.index, dtype=bool)


def _yueyue_flags(frame: pd.DataFrame, features: pd.DataFrame) -> pd.Series:
    flags = np.zeros(len(frame), dtype=bool)
    high = frame["high"].to_numpy(dtype=float)
    low = frame["low"].to_numpy(dtype=float)
    open_ = frame["open"].to_numpy(dtype=float)
    close = frame["close"].to_numpy(dtype=float)
    volume = frame["volume"]
    inclusive_volume_mean = volume.rolling(10, min_periods=5).mean().to_numpy(dtype=float)
    huge = volume.to_numpy(dtype=float) > inclusive_volume_mean * 2.0

    for position in range(34, len(frame)):
        start = position - 19
        platform_low = float(np.nanmin(low[start : position + 1]))
        platform_high = float(np.nanmax(high[start : position + 1]))
        amplitude = (platform_high - platform_low) / max(platform_low, 1.0)
        if amplitude > 0.16:
            continue
        huge_window = huge[start : position + 1]
        count = int(np.sum(huge_window))
        yang_count = int(
            np.sum(
                huge_window
                & (close[start : position + 1] > open_[start : position + 1])
            )
        )
        flags[position] = bool(count >= 2 and yang_count / max(count, 1) >= 0.5)
    return pd.Series(flags, index=frame.index, dtype=bool)


def compute_canonical_z_signal_flags(
    daily: pd.DataFrame,
    *,
    rule_features: pd.DataFrame | None = None,
) -> pd.DataFrame:
    """Compute the ten live-parity z-skill flags for every causal daily row.

    The returned frame contains ``symbol``, ``date``, and exactly the ten
    :data:`CANONICAL_Z_SIGNALS`.  ``symbol`` is an empty string when the input
    has neither ``symbol`` nor ``ts_code``.  Repeated hits remain repeated; no
    five-day cache cooldown is applied.
    """

    frame = _prepare_daily(daily)
    features = (
        compute_right_side_rule_features(frame).reset_index(drop=True)
        if rule_features is None
        else rule_features.reset_index(drop=True).copy()
    )
    if len(features) != len(frame):
        raise ValueError("rule_features must align one-to-one with daily rows")
    required_feature_columns = {
        "rs_pct_chg_1d",
        "rs_is_rise",
        "rs_vol_ratio_prev5",
        "rs_vol_ratio_prev",
        "rs_kdj_j",
        "rs_close_pos",
        "rs_amplitude_pct",
        "rs_zg_white",
        "rs_dg_yellow",
        "rs_bbi_distance_pct",
        "rs_bbi_slope_5d_pct",
    }
    missing_features = required_feature_columns - set(features.columns)
    if missing_features:
        raise ValueError(
            "rule_features missing canonical signal primitives: "
            f"{sorted(missing_features)}"
        )
    positions = pd.Series(np.arange(len(frame)), index=frame.index)

    pct = features["rs_pct_chg_1d"]
    is_rise = features["rs_is_rise"].fillna(False).astype(bool)
    vol_ratio_5 = features["rs_vol_ratio_prev5"]
    vol_ratio_prev = features["rs_vol_ratio_prev"]
    kdj_j = features["rs_kdj_j"]
    close_pos = features["rs_close_pos"]
    amplitude = features["rs_amplitude_pct"]
    body_pct = (frame["close"] - frame["open"]).abs().div(
        frame["pre_close"].clip(lower=1.0)
    ) * 100.0

    changan = (
        (positions >= 11)
        & (kdj_j.shift(2) < -13.0)
        & (pct.shift(1) >= 4.0)
        & is_rise.shift(1, fill_value=False)
        & (vol_ratio_5.shift(1) >= 1.4)
        & (kdj_j.shift(1) > kdj_j.shift(2))
        & (pct > 0.0)
        & (pct < 2.2)
        & (amplitude < 7.0)
        & (frame["volume"] <= frame["volume"].shift(1) * 0.55)
    )

    white = features["rs_zg_white"]
    yellow = features["rs_dg_yellow"]
    bowl_midpoint = (white + yellow) / 2.0
    golden_bowl = (
        (positions >= 119)
        & (yellow > 0.0)
        & (white > yellow * 1.005)
        & (frame["close"] >= yellow)
        & (frame["close"] <= bowl_midpoint)
        & ((frame["close"] - yellow).div(yellow) <= 0.04)
        & (kdj_j < 80.0)
    )

    phase_exhale = (pct > 0.0) & (vol_ratio_prev > 1.0)
    phase_inhale = (pct < 0.0) & (vol_ratio_prev < 1.0)
    live_higher_low = frame["low"] > pd.concat(
        [frame["low"].shift(6), frame["low"].shift(3)],
        axis=1,
    ).min(axis=1) * 0.98
    breathing = (
        (positions >= 15)
        & phase_exhale
        & (phase_exhale.rolling(7, min_periods=1).sum() >= 2)
        & (phase_inhale.rolling(7, min_periods=1).sum() >= 2)
        & live_higher_low
        & (pct >= 1.0)
        & (vol_ratio_prev >= 1.2)
        & (close_pos >= 0.60)
    )

    previous_high = frame["high"].shift(1).rolling(20, min_periods=1).max()
    previous_low = frame["low"].shift(1).rolling(20, min_periods=1).min()
    at_key = (frame["high"] >= previous_high * 0.98) | (
        frame["low"] <= previous_low * 1.02
    )
    key_volume_threshold = pd.Series(
        np.where(body_pct >= 7.0, 1.1, 1.3),
        index=frame.index,
    )
    key_k = (
        (positions >= 19)
        & (body_pct >= 3.0)
        & is_rise
        & (close_pos >= 0.75)
        & (pct >= 2.0)
        & (vol_ratio_5 >= key_volume_threshold)
        & at_key
    )

    historical_body = (frame["close"] - frame["open"]).abs().div(
        frame["pre_close"].replace(0, np.nan)
    ) * 100.0
    previous_six_body_mean = historical_body.shift(1).rolling(6, min_periods=6).mean()
    violence_k = (
        (positions >= 19)
        & (frame["low"] <= previous_low * 1.05)
        & is_rise
        & (pct > 0.0)
        & (close_pos >= 0.70)
        & (body_pct >= 5.0)
        & (body_pct > previous_six_body_mean * 2.0)
        & (vol_ratio_5 >= 2.0)
    )

    symbol_source = None
    for column in ("symbol", "ts_code"):
        if column in frame.columns and frame[column].notna().any():
            symbol_source = frame[column].fillna("").astype(str)
            break
    result = pd.DataFrame(
        {
            "symbol": symbol_source if symbol_source is not None else "",
            "date": frame["date"],
            "CHANGAN": changan,
            "PINGHANG": _pinghang_flags(frame, features),
            "DOUBLE_GUN": _double_gun_flags(frame, features),
            "GOLDEN_BOWL": golden_bowl,
            "BREATHING": breathing,
            "KENGQI": _kengqi_flags(frame, features),
            "ZAIHOU": _zaihou_flags(frame, features),
            "YUEYUE": _yueyue_flags(frame, features),
            "KEY_K": key_k,
            "VIOLENCE_K": violence_k,
        }
    )
    for signal in CANONICAL_Z_SIGNALS:
        result[signal] = result[signal].fillna(False).astype(bool)
    return result[["symbol", "date", *CANONICAL_Z_SIGNALS]].reset_index(drop=True)


def _normalise_signal_keys(frame: pd.DataFrame, *, name: str) -> pd.DataFrame:
    if not isinstance(frame, pd.DataFrame):
        raise TypeError(f"{name} must be a pandas DataFrame")
    if "date" not in frame.columns and "trade_date" not in frame.columns:
        raise ValueError(f"{name} must contain date or trade_date")
    symbol_column = "symbol" if "symbol" in frame.columns else "ts_code"
    if symbol_column not in frame.columns:
        raise ValueError(f"{name} must contain symbol or ts_code")
    date_column = "date" if "date" in frame.columns else "trade_date"
    out = frame.copy()
    out["symbol"] = out[symbol_column].fillna("").astype(str)
    out["date"] = _parse_dates(out[date_column])
    if out["date"].isna().any() or out["symbol"].eq("").any():
        raise ValueError(f"{name} contains invalid symbol/date keys")
    return out


def _or_available(frame: pd.DataFrame, columns: tuple[str, ...]) -> pd.Series:
    available = [column for column in columns if column in frame.columns]
    if not available:
        return pd.Series(False, index=frame.index, dtype=bool)
    return frame[available].fillna(False).astype(bool).any(axis=1)


def merge_canonical_signal_flags(
    z_flags: pd.DataFrame,
    family_rows: pd.DataFrame,
) -> pd.DataFrame:
    """Merge canonical z flags with the Web family-cache contract into 14 flags.

    Duplicate ``symbol/date`` rows are reduced with boolean OR.  The outer
    merge deliberately preserves zero-signal z rows so labels and future
    tradability can be joined before selecting the final candidate union.
    """

    z = _normalise_signal_keys(z_flags, name="z_flags")
    missing_z = set(CANONICAL_Z_SIGNALS) - set(z.columns)
    if missing_z:
        raise ValueError(f"z_flags missing canonical columns: {sorted(missing_z)}")
    for signal in CANONICAL_Z_SIGNALS:
        z[signal] = z[signal].fillna(False).astype(bool)
    z = z.groupby(["symbol", "date"], as_index=False, sort=False)[
        list(CANONICAL_Z_SIGNALS)
    ].max()

    family = _normalise_signal_keys(family_rows, name="family_rows")
    family_out = family[["symbol", "date"]].copy()
    family_out["B2"] = _or_available(
        family,
        ("B2", *B2_FAMILY_SOURCE_COLUMNS),
    )
    family_out["B3"] = _or_available(
        family,
        ("B3", *B3_FAMILY_SOURCE_COLUMNS),
    )
    for target, source in FAMILY_DIRECT_SOURCE_COLUMNS.items():
        family_out[target] = _or_available(family, (target, source))
    family_out = family_out.groupby(
        ["symbol", "date"],
        as_index=False,
        sort=False,
    )[["B2", "B3", "VEGAS", "TRIPLE_VOLUME_BREAKOUT"]].max()

    merged = z.merge(family_out, on=["symbol", "date"], how="outer")
    for signal in CANONICAL_RIGHT_SIDE_SIGNALS:
        if signal not in merged.columns:
            merged[signal] = False
        merged[signal] = merged[signal].fillna(False).astype(bool)
    return (
        merged[["symbol", "date", *CANONICAL_RIGHT_SIDE_SIGNALS]]
        .sort_values(["date", "symbol"], kind="stable")
        .reset_index(drop=True)
    )


__all__ = [
    "B2_FAMILY_SOURCE_COLUMNS",
    "B3_FAMILY_SOURCE_COLUMNS",
    "CANONICAL_RIGHT_SIDE_SIGNALS",
    "CANONICAL_SIGNAL_SCHEMA_VERSION",
    "CANONICAL_Z_SIGNALS",
    "FAMILY_DIRECT_SOURCE_COLUMNS",
    "SIGNAL_CONTRACT_NOTES",
    "compute_canonical_z_signal_flags",
    "merge_canonical_signal_flags",
]
