from __future__ import annotations

import json
import math
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from quant.strategies.convertible_bond.backtest import (  # noqa: E402
    ConvertibleBondBacktestConfig,
    write_backtest_outputs,
)
from quant.strategies.convertible_bond.grid import (  # noqa: E402
    HoldingGridConfig,
    backtest_holding_grid,
)

DATA_DIR = PROJECT_ROOT / "data/convertible_bond/tushare"
DAILY_PATH = DATA_DIR / "cb_daily_20180101_20260616.parquet"
BASIC_PATH = DATA_DIR / "cb_basic_all.parquet"
CALL_PATH = DATA_DIR / "cb_call_20180101_20260616.parquet"
OUTPUT_ROOT = PROJECT_ROOT / "reports/convertible_bond/ladder_grid_iteration"


def json_safe(value):
    if isinstance(value, float) and not math.isfinite(value):
        return None
    if isinstance(value, dict):
        return {key: json_safe(item) for key, item in value.items()}
    if isinstance(value, list):
        return [json_safe(item) for item in value]
    return value


def ladder_configs() -> list[HoldingGridConfig]:
    return [
        HoldingGridConfig(
            name="baseline_balanced_block",
            top_n=8,
            max_holdings=12,
            max_total_weight=0.85,
            max_position_weight=0.15,
            max_entry_price=114.0,
            min_premium_rate=-1.0,
            max_premium_rate=22.0,
            max_double_low=134.0,
            max_price_position_252=0.30,
            min_drawdown_from_252_high=0.08,
            min_amount=4_000.0,
            min_momentum_20d=-0.08,
            market_risk_mode="block_downtrend",
            exit_price=128.0,
            exit_premium_rate=40.0,
            exit_double_low=158.0,
            exit_price_position_252=0.76,
            min_credit_rating="AA-",
        ),
        HoldingGridConfig(
            name="ladder_entry_tp_block",
            top_n=8,
            max_holdings=12,
            max_total_weight=0.85,
            max_position_weight=0.15,
            max_entry_price=114.0,
            min_premium_rate=-1.0,
            max_premium_rate=22.0,
            max_double_low=134.0,
            max_price_position_252=0.30,
            min_drawdown_from_252_high=0.08,
            min_amount=4_000.0,
            min_momentum_20d=-0.08,
            market_risk_mode="block_downtrend",
            exit_price=132.0,
            exit_premium_rate=45.0,
            exit_double_low=165.0,
            exit_price_position_252=0.82,
            min_credit_rating="AA-",
            initial_entry_fraction=0.50,
            add_on_drawdown_step=0.04,
            add_position_fraction=0.25,
            max_grid_position_fraction=1.00,
            take_profit_1=0.08,
            take_profit_1_keep_fraction=0.50,
            take_profit_2=0.18,
        ),
        HoldingGridConfig(
            name="ladder_deeper_grid_block",
            top_n=10,
            max_holdings=16,
            max_total_weight=0.90,
            max_position_weight=0.13,
            max_entry_price=116.0,
            min_premium_rate=-2.0,
            max_premium_rate=24.0,
            max_double_low=138.0,
            max_price_position_252=0.34,
            min_drawdown_from_252_high=0.07,
            min_amount=3_000.0,
            min_momentum_20d=-0.10,
            market_risk_mode="block_downtrend",
            exit_price=134.0,
            exit_premium_rate=48.0,
            exit_double_low=170.0,
            exit_price_position_252=0.84,
            min_credit_rating="AA-",
            initial_entry_fraction=0.45,
            add_on_drawdown_step=0.035,
            add_position_fraction=0.25,
            max_grid_position_fraction=1.00,
            take_profit_1=0.07,
            take_profit_1_keep_fraction=0.55,
            take_profit_2=0.18,
        ),
        HoldingGridConfig(
            name="expanded_pool_ladder_block",
            top_n=14,
            max_holdings=22,
            max_total_weight=0.95,
            max_position_weight=0.10,
            max_entry_price=118.0,
            min_premium_rate=-3.0,
            max_premium_rate=28.0,
            max_double_low=144.0,
            max_price_position_252=0.40,
            min_drawdown_from_252_high=0.06,
            min_amount=1_500.0,
            min_remaining_size=0.8,
            min_momentum_20d=-0.12,
            market_risk_mode="block_downtrend",
            exit_price=136.0,
            exit_premium_rate=52.0,
            exit_double_low=176.0,
            exit_price_position_252=0.86,
            min_credit_rating="A+",
            initial_entry_fraction=0.40,
            add_on_drawdown_step=0.035,
            add_position_fraction=0.20,
            max_grid_position_fraction=1.00,
            take_profit_1=0.07,
            take_profit_1_keep_fraction=0.55,
            take_profit_2=0.18,
        ),
        HoldingGridConfig(
            name="guarded_expanded_ladder_block",
            top_n=12,
            max_holdings=18,
            max_total_weight=0.90,
            max_position_weight=0.10,
            max_entry_price=116.0,
            min_premium_rate=-2.0,
            max_premium_rate=24.0,
            max_double_low=138.0,
            max_price_position_252=0.34,
            min_drawdown_from_252_high=0.07,
            min_amount=2_000.0,
            min_remaining_size=1.0,
            min_momentum_20d=-0.10,
            market_risk_mode="block_downtrend",
            exit_price=134.0,
            exit_premium_rate=48.0,
            exit_double_low=170.0,
            exit_price_position_252=0.84,
            exit_floor_price=98.0,
            exit_momentum_20d=-0.12,
            stop_loss_from_entry=0.08,
            min_credit_rating="AA-",
            initial_entry_fraction=0.40,
            add_on_drawdown_step=0.035,
            add_position_fraction=0.20,
            max_grid_position_fraction=1.00,
            take_profit_1=0.07,
            take_profit_1_keep_fraction=0.55,
            take_profit_2=0.18,
        ),
        HoldingGridConfig(
            name="floor98_expanded_ladder_block",
            top_n=14,
            max_holdings=22,
            max_total_weight=0.95,
            max_position_weight=0.10,
            max_entry_price=118.0,
            min_premium_rate=-3.0,
            max_premium_rate=28.0,
            max_double_low=144.0,
            max_price_position_252=0.40,
            min_drawdown_from_252_high=0.06,
            min_amount=1_500.0,
            min_remaining_size=0.8,
            min_momentum_20d=-0.12,
            market_risk_mode="block_downtrend",
            exit_price=136.0,
            exit_premium_rate=52.0,
            exit_double_low=176.0,
            exit_price_position_252=0.86,
            exit_floor_price=98.0,
            min_credit_rating="A+",
            initial_entry_fraction=0.40,
            add_on_drawdown_step=0.035,
            add_position_fraction=0.20,
            max_grid_position_fraction=1.00,
            take_profit_1=0.07,
            take_profit_1_keep_fraction=0.55,
            take_profit_2=0.18,
        ),
        HoldingGridConfig(
            name="strict_dynamic_floor98_grid",
            top_n=None,
            max_holdings=22,
            max_total_weight=0.95,
            max_position_weight=0.10,
            max_entry_price=118.0,
            min_premium_rate=-3.0,
            max_premium_rate=28.0,
            max_double_low=144.0,
            max_price_position_252=0.40,
            min_drawdown_from_252_high=0.06,
            min_amount=1_500.0,
            min_remaining_size=0.8,
            min_momentum_20d=-0.12,
            market_risk_mode="block_downtrend",
            exit_price=136.0,
            exit_premium_rate=52.0,
            exit_double_low=176.0,
            exit_price_position_252=0.86,
            exit_floor_price=98.0,
            min_credit_rating="A+",
            initial_entry_fraction=0.40,
            add_on_drawdown_step=0.035,
            add_position_fraction=0.20,
            max_grid_position_fraction=1.00,
            dynamic_grid=True,
            low_risk_grid_step=0.030,
            medium_risk_grid_step=0.040,
            high_risk_grid_step=0.055,
            low_risk_position_scale=1.00,
            medium_risk_position_scale=0.80,
            high_risk_position_scale=0.55,
            take_profit_1=0.07,
            take_profit_1_keep_fraction=0.55,
            take_profit_2=0.18,
        ),
        HoldingGridConfig(
            name="strict_dynamic_floor96_grid",
            top_n=None,
            max_holdings=22,
            max_total_weight=0.95,
            max_position_weight=0.10,
            max_entry_price=118.0,
            min_premium_rate=-3.0,
            max_premium_rate=28.0,
            max_double_low=144.0,
            max_price_position_252=0.40,
            min_drawdown_from_252_high=0.06,
            min_amount=1_500.0,
            min_remaining_size=0.8,
            min_momentum_20d=-0.12,
            market_risk_mode="block_downtrend",
            exit_price=136.0,
            exit_premium_rate=52.0,
            exit_double_low=176.0,
            exit_price_position_252=0.86,
            exit_floor_price=96.0,
            min_credit_rating="A+",
            initial_entry_fraction=0.40,
            add_on_drawdown_step=0.035,
            add_position_fraction=0.20,
            max_grid_position_fraction=1.00,
            dynamic_grid=True,
            low_risk_grid_step=0.030,
            medium_risk_grid_step=0.040,
            high_risk_grid_step=0.055,
            low_risk_position_scale=1.00,
            medium_risk_position_scale=0.80,
            high_risk_position_scale=0.55,
            take_profit_1=0.07,
            take_profit_1_keep_fraction=0.55,
            take_profit_2=0.18,
        ),
        HoldingGridConfig(
            name="strict_dynamic_floor94_grid",
            top_n=None,
            max_holdings=22,
            max_total_weight=0.95,
            max_position_weight=0.10,
            max_entry_price=118.0,
            min_premium_rate=-3.0,
            max_premium_rate=28.0,
            max_double_low=144.0,
            max_price_position_252=0.40,
            min_drawdown_from_252_high=0.06,
            min_amount=1_500.0,
            min_remaining_size=0.8,
            min_momentum_20d=-0.12,
            market_risk_mode="block_downtrend",
            exit_price=136.0,
            exit_premium_rate=52.0,
            exit_double_low=176.0,
            exit_price_position_252=0.86,
            exit_floor_price=94.0,
            min_credit_rating="A+",
            initial_entry_fraction=0.40,
            add_on_drawdown_step=0.035,
            add_position_fraction=0.20,
            max_grid_position_fraction=1.00,
            dynamic_grid=True,
            low_risk_grid_step=0.030,
            medium_risk_grid_step=0.040,
            high_risk_grid_step=0.055,
            low_risk_position_scale=1.00,
            medium_risk_position_scale=0.80,
            high_risk_position_scale=0.55,
            take_profit_1=0.07,
            take_profit_1_keep_fraction=0.55,
            take_profit_2=0.18,
        ),
        HoldingGridConfig(
            name="strict_dynamic_no_floor_grid",
            top_n=None,
            max_holdings=22,
            max_total_weight=0.95,
            max_position_weight=0.10,
            max_entry_price=118.0,
            min_premium_rate=-3.0,
            max_premium_rate=28.0,
            max_double_low=144.0,
            max_price_position_252=0.40,
            min_drawdown_from_252_high=0.06,
            min_amount=1_500.0,
            min_remaining_size=0.8,
            min_momentum_20d=-0.12,
            market_risk_mode="block_downtrend",
            exit_price=136.0,
            exit_premium_rate=52.0,
            exit_double_low=176.0,
            exit_price_position_252=0.86,
            exit_floor_price=None,
            min_credit_rating="A+",
            initial_entry_fraction=0.40,
            add_on_drawdown_step=0.035,
            add_position_fraction=0.20,
            max_grid_position_fraction=1.00,
            dynamic_grid=True,
            low_risk_grid_step=0.030,
            medium_risk_grid_step=0.040,
            high_risk_grid_step=0.055,
            low_risk_position_scale=1.00,
            medium_risk_position_scale=0.80,
            high_risk_position_scale=0.55,
            take_profit_1=0.07,
            take_profit_1_keep_fraction=0.55,
            take_profit_2=0.18,
        ),
        HoldingGridConfig(
            name="defensive_low_price_dynamic_grid",
            top_n=None,
            max_holdings=16,
            max_total_weight=0.80,
            max_position_weight=0.12,
            max_entry_price=112.0,
            min_premium_rate=-3.0,
            max_premium_rate=18.0,
            max_double_low=130.0,
            max_price_position_252=0.28,
            min_drawdown_from_252_high=0.08,
            min_amount=2_500.0,
            min_remaining_size=1.0,
            min_momentum_20d=-0.08,
            market_risk_mode="block_downtrend",
            exit_price=128.0,
            exit_premium_rate=38.0,
            exit_double_low=158.0,
            exit_price_position_252=0.76,
            exit_floor_price=100.0,
            min_credit_rating="AA-",
            initial_entry_fraction=0.45,
            add_on_drawdown_step=0.030,
            add_position_fraction=0.20,
            max_grid_position_fraction=1.00,
            dynamic_grid=True,
            low_risk_grid_step=0.025,
            medium_risk_grid_step=0.035,
            high_risk_grid_step=0.050,
            low_risk_position_scale=1.00,
            medium_risk_position_scale=0.75,
            high_risk_position_scale=0.45,
            take_profit_1=0.06,
            take_profit_1_keep_fraction=0.55,
            take_profit_2=0.14,
        ),
        HoldingGridConfig(
            name="recovery_scaled_dynamic_grid",
            top_n=None,
            max_holdings=24,
            max_total_weight=0.90,
            max_position_weight=0.08,
            max_entry_price=120.0,
            min_premium_rate=-3.0,
            max_premium_rate=30.0,
            max_double_low=150.0,
            max_price_position_252=0.45,
            min_drawdown_from_252_high=0.05,
            min_amount=1_500.0,
            min_remaining_size=0.8,
            min_momentum_20d=-0.10,
            market_risk_mode="scale_downtrend",
            market_entry_scale_weak=0.20,
            market_entry_scale_strong=1.0,
            exit_price=138.0,
            exit_premium_rate=55.0,
            exit_double_low=180.0,
            exit_price_position_252=0.88,
            exit_floor_price=98.0,
            min_credit_rating="A+",
            initial_entry_fraction=0.35,
            add_on_drawdown_step=0.040,
            add_position_fraction=0.20,
            max_grid_position_fraction=1.00,
            dynamic_grid=True,
            low_risk_grid_step=0.030,
            medium_risk_grid_step=0.045,
            high_risk_grid_step=0.060,
            low_risk_position_scale=1.00,
            medium_risk_position_scale=0.75,
            high_risk_position_scale=0.50,
            take_profit_1=0.08,
            take_profit_1_keep_fraction=0.50,
            take_profit_2=0.20,
        ),
        HoldingGridConfig(
            name="guarded_expanded_ladder_scaled",
            top_n=12,
            max_holdings=18,
            max_total_weight=0.90,
            max_position_weight=0.10,
            max_entry_price=116.0,
            min_premium_rate=-2.0,
            max_premium_rate=24.0,
            max_double_low=138.0,
            max_price_position_252=0.34,
            min_drawdown_from_252_high=0.07,
            min_amount=2_000.0,
            min_remaining_size=1.0,
            min_momentum_20d=-0.10,
            market_risk_mode="scale_downtrend",
            market_entry_scale_weak=0.20,
            market_entry_scale_strong=1.0,
            exit_price=134.0,
            exit_premium_rate=48.0,
            exit_double_low=170.0,
            exit_price_position_252=0.84,
            exit_floor_price=98.0,
            exit_momentum_20d=-0.12,
            stop_loss_from_entry=0.08,
            min_credit_rating="AA-",
            initial_entry_fraction=0.40,
            add_on_drawdown_step=0.035,
            add_position_fraction=0.20,
            max_grid_position_fraction=1.00,
            take_profit_1=0.07,
            take_profit_1_keep_fraction=0.55,
            take_profit_2=0.18,
        ),
        HoldingGridConfig(
            name="expanded_pool_ladder_scaled",
            top_n=14,
            max_holdings=22,
            max_total_weight=0.95,
            max_position_weight=0.10,
            max_entry_price=118.0,
            min_premium_rate=-3.0,
            max_premium_rate=28.0,
            max_double_low=144.0,
            max_price_position_252=0.40,
            min_drawdown_from_252_high=0.06,
            min_amount=1_500.0,
            min_remaining_size=0.8,
            min_momentum_20d=-0.12,
            market_risk_mode="scale_downtrend",
            market_entry_scale_weak=0.25,
            market_entry_scale_strong=1.0,
            exit_price=136.0,
            exit_premium_rate=52.0,
            exit_double_low=176.0,
            exit_price_position_252=0.86,
            min_credit_rating="A+",
            initial_entry_fraction=0.40,
            add_on_drawdown_step=0.035,
            add_position_fraction=0.20,
            max_grid_position_fraction=1.00,
            take_profit_1=0.07,
            take_profit_1_keep_fraction=0.55,
            take_profit_2=0.18,
        ),
    ]


def run_variant(
    daily: pd.DataFrame,
    basic: pd.DataFrame,
    call: pd.DataFrame,
    grid_config: HoldingGridConfig,
    start_date: str,
    end_date: str,
) -> dict:
    backtest_config = ConvertibleBondBacktestConfig(
        start_date=start_date,
        end_date=end_date,
        rebalance="monthly",
        commission_rate=0.0002,
        slippage_rate=0.0002,
        initial_cash=1_000_000.0,
    )
    result = backtest_holding_grid(
        daily=daily,
        basic=basic,
        call=call,
        backtest_config=backtest_config,
        grid_config=grid_config,
    )
    out_dir = OUTPUT_ROOT / f"{grid_config.name}_{start_date}_{end_date}_monthly"
    paths = write_backtest_outputs(result, out_dir)
    summary = dict(result.summary)
    summary.update(
        {
            "variant": grid_config.name,
            "rebalance": "monthly",
            "summary_path": str(paths["summary"]),
            "position_trades_path": str(paths["position_trades"]),
        }
    )
    return summary


def main() -> None:
    daily = pd.read_parquet(DAILY_PATH)
    basic = pd.read_parquet(BASIC_PATH)
    call = pd.read_parquet(CALL_PATH) if CALL_PATH.exists() else pd.DataFrame()
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    jobs = [
        (config, start_date)
        for config in ladder_configs()
        for start_date in ["20200101", "20240101"]
    ]
    summaries: list[dict] = []
    for index, (config, start_date) in enumerate(jobs, start=1):
        print(f"[{index}/{len(jobs)}] {config.name} {start_date}", flush=True)
        summaries.append(
            run_variant(
                daily=daily,
                basic=basic,
                call=call,
                grid_config=config,
                start_date=start_date,
                end_date="20260616",
            )
        )
    summary_frame = pd.DataFrame(summaries)
    summary_path = OUTPUT_ROOT / "iteration_summary.csv"
    summary_frame.to_csv(summary_path, index=False)
    columns = [
        "variant",
        "start_date",
        "total_return",
        "annual_return",
        "max_drawdown",
        "closed_position_trades",
        "position_win_rate",
        "position_profit_factor",
        "average_position_return",
        "median_position_return",
        "average_holding_days",
        "average_exposure",
        "trade_count",
    ]
    ranked = summary_frame.sort_values(
        ["start_date", "total_return", "max_drawdown"],
        ascending=[True, False, False],
    )
    print(
        json.dumps(
            json_safe(
                {
                    "summary_path": str(summary_path),
                    "ranked": ranked[columns].to_dict(orient="records"),
                }
            ),
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
