#!/usr/bin/env python3
"""Grid-search drawdown/decline thresholds for blood-chip signal selection.

The script reuses the existing blood-chip signal pipeline and applies a
post-filter at each shock event:

- 252-day drawdown must reach at least a configured minimum
- 120-day drawdown must reach at least a configured minimum
- 5-day decline from shock row must exceed a configured minimum
- 10-day decline from shock row must exceed a configured minimum

Then each candidate set is run through the existing long-horizon blood-chip
backtest across fixed periods.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from quant.research.blood_chip import (
    BloodChipBacktestConfig,
    load_benchmark,
    run_blood_chip_backtest,
    summarize_blood_chip_result,
)


DEFAULT_FEATURE_COLUMNS: tuple[str, ...] = (
    "ts_code",
    "date",
    "trade_date",
    "open",
    "high",
    "low",
    "close",
    "adjusted_open",
    "adjusted_high",
    "adjusted_low",
    "adjusted_close",
)

PERIODS = (
    ("development_2014_2019", "2014-01-01", "2019-12-31"),
    ("iteration_2020_2022", "2020-01-01", "2022-12-30"),
    ("seen_2023_2026", "2023-01-03", "2026-02-06"),
)


@dataclass(frozen=True)
class DropThroughGrid:
    drawdown_252: float
    drawdown_120: float
    drop_5d: float
    drop_10d: float

    @property
    def name(self) -> str:
        return (
            f"dd252={self.drawdown_252:.0%}|dd120={self.drawdown_120:.0%}"
            f"|5d={self.drop_5d:.0%}|10d={self.drop_10d:.0%}"
        )


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Optimize blood-chip drop-through thresholds by historical backtest."
    )
    parser.add_argument(
        "--features", default="data/research/blood_chip/features.parquet",
        help="Cached blood-chip feature parquet.",
    )
    parser.add_argument(
        "--signals", default="reports/research/blood_chip_exhaustion/path_signals.parquet",
        help="Signal file generated by add_blood_chip_path_features.",
    )
    parser.add_argument(
        "--benchmark", default="data/raw/index_000300.SH.parquet",
        help="Benchmark parquet with trade_date/close/pct_chg.",
    )
    parser.add_argument(
        "--output-dir", default="reports/research/blood_chip_dropthrough_grid",
        help="Output directory for grid metrics and report.",
    )
    parser.add_argument(
        "--dd252", default="0.60,0.65,0.70,0.75",
        help="Comma-separated drawdown grid (fraction, e.g. 0.70 for 70%).",
    )
    parser.add_argument(
        "--dd120", default="0.20,0.25",
        help="Comma-separated 120-day drawdown grid.",
    )
    parser.add_argument(
        "--drop5", default="0.08,0.12",
        help="Comma-separated 5-day shock decline grid (absolute decline).",
    )
    parser.add_argument(
        "--drop10", default="0.12,0.16",
        help="Comma-separated 10-day shock decline grid (absolute decline).",
    )
    parser.add_argument(
        "--min-signals", type=int, default=80,
        help="Skip threshold rows with fewer base candidates than this number.",
    )
    parser.add_argument(
        "--top-n", type=int, default=30,
        help="Write top-N combos by score.",
    )
    return parser.parse_args()


def _parse_grid(value: str) -> tuple[float, ...]:
    values = sorted({float(item.strip()) for item in value.split(",") if item.strip()})
    if not values:
        raise ValueError("threshold grid cannot be empty")
    return tuple(values)


def _safe_float(value: object) -> float | None:
    number = pd.to_numeric(value, errors="coerce")
    if pd.isna(number) or not np.isfinite(float(number)):
        return None
    return float(number)


def _attach_signal_drawdown_features(
    signals: pd.DataFrame,
    features: pd.DataFrame,
) -> pd.DataFrame:
    """Attach shock-date drawdown/decline metrics to signals."""

    frame = features[
        [
            "ts_code",
            "date",
            "adjusted_close",
            "_rolling_drawdown_252",
            "_rolling_drawdown_120",
            "_return_5d",
            "_return_10d",
        ]
    ].copy()
    frame["ts_code"] = frame["ts_code"].astype(str)

    signal_frame = signals.copy()
    signal_frame["ts_code"] = signal_frame["ts_code"].astype(str)
    signal_frame["shock_date"] = pd.to_datetime(signal_frame["shock_date"], errors="coerce")

    shock_lookup = frame.rename(
        columns={
            "date": "_shock_date",
            "_rolling_drawdown_252": "shock_drawdown_252",
            "_rolling_drawdown_120": "shock_drawdown_120",
            "_return_5d": "shock_return_5d",
            "_return_10d": "shock_return_10d",
        },
    )
    out = signal_frame.merge(
        shock_lookup[
            ["ts_code", "_shock_date", "shock_drawdown_252", "shock_drawdown_120", "shock_return_5d", "shock_return_10d"]
        ],
        left_on=["ts_code", "shock_date"],
        right_on=["ts_code", "_shock_date"],
        how="left",
    )
    return out.drop(columns=["_shock_date"])


def _build_backtest_data(features_path: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    print(f"loading features: {features_path}", flush=True)
    frame = pd.read_parquet(features_path)
    frame = frame.copy()
    frame["date"] = pd.to_datetime(frame["date"], errors="coerce")
    frame = frame.sort_values(["ts_code", "date"], kind="mergesort").reset_index(drop=True)

    groups = frame["ts_code"]
    drawdown_252 = (
        frame.groupby(groups, sort=False)["adjusted_close"]
        .rolling(252, min_periods=252)
        .max()
        .reset_index(level=0, drop=True)
    )
    drawdown_120 = (
        frame.groupby(groups, sort=False)["adjusted_close"]
        .rolling(120, min_periods=120)
        .max()
        .reset_index(level=0, drop=True)
    )
    frame["_rolling_drawdown_252"] = frame["adjusted_close"] / drawdown_252 - 1.0
    frame["_rolling_drawdown_120"] = frame["adjusted_close"] / drawdown_120 - 1.0
    frame["_return_5d"] = (
        frame["adjusted_close"] / frame.groupby(groups, sort=False)["adjusted_close"].shift(5)
        - 1.0
    )
    frame["_return_10d"] = (
        frame["adjusted_close"] / frame.groupby(groups, sort=False)["adjusted_close"].shift(10)
        - 1.0
    )

    daily = frame.loc[:, DEFAULT_FEATURE_COLUMNS].copy()
    return frame, daily


def _build_grid(
    dd252: tuple[float, ...],
    dd120: tuple[float, ...],
    drop5: tuple[float, ...],
    drop10: tuple[float, ...],
) -> list[DropThroughGrid]:
    return [
        DropThroughGrid(
            drawdown_252=value_dd252,
            drawdown_120=value_dd120,
            drop_5d=value_drop5,
            drop_10d=value_drop10,
        )
        for value_dd252 in dd252
        for value_dd120 in dd120
        for value_drop5 in drop5
        for value_drop10 in drop10
    ]


def _safe_rate(value: pd.Series | float | np.ndarray, default: float = 0.0) -> float:
    try:
        numbers = pd.to_numeric(pd.Series(value), errors="coerce").dropna()
    except Exception:
        return default
    if numbers.empty:
        return default
    return float(numbers.mean())


def _score_combo(row: pd.Series) -> float:
    """Score emphasises iteration, with mild holdout and risk penalties."""

    iter_ret = float(row.get("total_return_iteration_2020_2022", np.nan))
    dev_ret = float(row.get("total_return_development_2014_2019", np.nan))
    holdout_ret = float(row.get("total_return_seen_2023_2026", 0.0))
    if not np.isfinite(iter_ret):
        return np.nan
    if not np.isfinite(dev_ret):
        dev_ret = 0.0
    if not np.isfinite(holdout_ret):
        holdout_ret = 0.0

    iter_dd = float(row.get("maximum_drawdown_iteration_2020_2022", np.nan))
    holdout_dd = float(row.get("maximum_drawdown_seen_2023_2026", np.nan))
    if not np.isfinite(iter_dd):
        return np.nan
    if not np.isfinite(holdout_dd):
        holdout_dd = 0.0
    iter_trade_risk = max(0.0, -iter_dd - 0.28)
    holdout_risk = max(0.0, -holdout_dd - 0.34)
    return (
        0.45 * iter_ret
        + 0.30 * dev_ret
        + 0.25 * holdout_ret
        - 2.0 * iter_trade_risk
        - 1.5 * holdout_risk
    )


def _selection_quality(row: pd.Series) -> float:
    # Penalize combos with weak sample size and weak win-rate stability.
    iter_trades = float(row.get("trades_iteration_2020_2022", 0.0) or 0.0)
    dev_trades = float(row.get("trades_development_2014_2019", 0.0) or 0.0)
    win_iter = _safe_rate(pd.to_numeric(row.get("win_rate_iteration_2020_2022"), errors="coerce"), 0.0)
    win_dev = _safe_rate(pd.to_numeric(row.get("win_rate_development_2014_2019"), errors="coerce"), 0.0)
    return (
        1.0 / (1.0 + np.exp(-(iter_trades + dev_trades) / 40.0))
        * 0.5 * (win_iter + win_dev)
    )


def _row_score(row: pd.Series) -> float:
    if pd.isna(row.get("total_return_iteration_2020_2022")):
        return np.nan
    base = _score_combo(row)
    if pd.isna(base):
        return np.nan
    quality = _selection_quality(row)
    return float(base) + 0.4 * quality


def _emit_json(path: Path, value: dict[str, Any]) -> None:
    path.write_text(
        json.dumps(_to_json(value), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def _to_json(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): _to_json(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_to_json(item) for item in value]
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return float(value) if np.isfinite(value) else None
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    return value


def _format_pct(value: Any) -> str:
    value = pd.to_numeric(value, errors="coerce")
    if pd.isna(value):
        return "—"
    return f"{float(value):.2%}"


def _format_score(value: float | int | None) -> str:
    if value is None or pd.isna(value):
        return "—"
    return f"{float(value):.4f}"


def _write_markdown(
    rows: pd.DataFrame,
    output_dir: Path,
    top_n: int,
) -> None:
    top = rows.head(top_n).copy()
    lines = [
        "# 带血筹跌透阈值网格搜索（历史全部）",
        "",
        "筛选逻辑：",
        "- 先在信号层按 `shock_date` 计算跌幅门槛",
        "- 再用现有 `run_blood_chip_backtest` 对三阶段区间回测",
        "",
    ]
    if top.empty:
        lines.append("无可用组合通过指标约束。")
        output_dir.joinpath("grid_search_report.md").write_text(
            "\n".join(lines) + "\n", encoding="utf-8"
        )
        return
    lines.extend(
        [
            "## Top 结果（按综合分）",
            "",
            "| 名称 | 规则 | 开发期交易数 | 迭代期交易数 | 看见期交易数 | 开发期总收益 | 迭代期总收益 | 看见期总收益 | 最大回撤(迭代) | 平均分 |",
            "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for _, row in top.iterrows():
        lines.append(
            "| {name} | {combo} | {dev_tr} | {it_tr} | {seen_tr} | {dev_ret} | {it_ret} | {seen_ret} | {it_dd} | {score} |".format(
                name=row.get("name", ""),
                combo=row.get("combo", ""),
                dev_tr=int(row.get("trades_development_2014_2019", 0)),
                it_tr=int(row.get("trades_iteration_2020_2022", 0)),
                seen_tr=int(row.get("trades_seen_2023_2026", 0)),
                dev_ret=_format_pct(row.get("total_return_development_2014_2019")),
                it_ret=_format_pct(row.get("total_return_iteration_2020_2022")),
                seen_ret=_format_pct(row.get("total_return_seen_2023_2026")),
                it_dd=_format_pct(row.get("maximum_drawdown_iteration_2020_2022")),
                score=_format_score(row.get("selection_score")),
            )
        )
    lines.extend(
        [
            "",
            "## 约束（用于稳定性筛选）",
            "",
            "- 开发期交易数 ≥ 40",
            "- 迭代期交易数 ≥ 20",
            "- 迭代期最大回撤 ≥ -28%",
            "- 迭代/开发期收益都需为正",
            "",
            "## 说明",
            "",
            "- “看见期”仅用于稳健性观察，不参与门槛参数确定。",
            "- 阈值含义（正向输入）：dd252=0.70 代表“252 日跌幅 ≥ 70%”。",
        ]
    )
    output_dir.joinpath("grid_search_report.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def main() -> None:
    args = _parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    dd252_values = _parse_grid(args.dd252)
    dd120_values = _parse_grid(args.dd120)
    drop5_values = _parse_grid(args.drop5)
    drop10_values = _parse_grid(args.drop10)
    print(
        f"grid sizes: dd252={len(dd252_values)} dd120={len(dd120_values)} "
        f"drop5={len(drop5_values)} drop10={len(drop10_values)}",
        flush=True,
    )

    features_frame, daily = _build_backtest_data(args.features)
    benchmark = load_benchmark(args.benchmark, "2014-01-01", "2026-02-06")
    signals = pd.read_parquet(args.signals)
    signals = _attach_signal_drawdown_features(signals, features_frame)
    signals = signals.loc[
        signals["shock_date"].notna()
        & signals["shock_drawdown_252"].notna()
        & signals["shock_drawdown_120"].notna()
        & signals["shock_return_5d"].notna()
        & signals["shock_return_10d"].notna()
    ].copy()

    backtest_config = BloodChipBacktestConfig()
    grid = _build_grid(dd252_values, dd120_values, drop5_values, drop10_values)
    rows: list[dict[str, Any]] = []
    total = len(grid)
    for idx, combo in enumerate(grid, start=1):
        print(
            f"[{idx:>3}/{total}] dd252={combo.drawdown_252:.2f}, dd120={combo.drawdown_120:.2f}, "
            f"r5={combo.drop_5d:.2%}, r10={combo.drop_10d:.2%}",
            flush=True,
        )

        mask = (
            (signals["shock_drawdown_252"] <= -combo.drawdown_252)
            & (signals["shock_drawdown_120"] <= -combo.drawdown_120)
            & (signals["shock_return_5d"] <= -combo.drop_5d)
            & (signals["shock_return_10d"] <= -combo.drop_10d)
        )
        subset = signals.loc[mask].copy()
        if len(subset) < args.min_signals:
            continue
        print(f"  selected signals: {len(subset):,}", flush=True)

        row: dict[str, Any] = {
            "combo": combo.name,
            "drawdown_252": combo.drawdown_252,
            "drawdown_120": combo.drawdown_120,
            "drop_5d": combo.drop_5d,
            "drop_10d": combo.drop_10d,
            "signals_selected": int(len(subset)),
        }
        for period_name, start, end in PERIODS:
            result = run_blood_chip_backtest(
                daily,
                subset,
                backtest_config,
                entry_start=start,
                entry_end=end,
            )
            metrics = summarize_blood_chip_result(result, benchmark)
            row[f"trades_{period_name}"] = int(metrics.get("trades", 0))
            row[f"win_rate_{period_name}"] = float(metrics.get("win_rate", np.nan))
            row[f"total_return_{period_name}"] = float(metrics.get("total_return", np.nan))
            row[f"maximum_drawdown_{period_name}"] = float(
                metrics.get("maximum_drawdown", np.nan)
            )
            row[f"profit_factor_{period_name}"] = float(metrics.get("profit_factor", np.nan))
        rows.append(row)

    metric_frame = pd.DataFrame(rows).sort_values(
        ["combo"], key=lambda s: s.str.lower() if s.dtype == "object" else s
    )
    if metric_frame.empty:
        raise RuntimeError("No threshold combination passed the minimal signal filter.")
    metric_frame["selection_score"] = metric_frame.apply(_row_score, axis=1)
    metric_frame.to_csv(output_dir / "grid_metrics.csv", index=False)
    metric_frame.to_parquet(output_dir / "grid_metrics.parquet", index=False)

    # Constraint filter for candidate selection.
    candidates = metric_frame.copy()
    constraint_mask = (
        (candidates["trades_development_2014_2019"] >= 40)
        & (candidates["trades_iteration_2020_2022"] >= 20)
        & (candidates["maximum_drawdown_iteration_2020_2022"] >= -0.28)
        & (candidates["total_return_iteration_2020_2022"] > 0)
        & (candidates["total_return_development_2014_2019"] > 0)
    )
    qualified = (
        candidates.loc[constraint_mask]
        .sort_values("selection_score", ascending=False)
        .reset_index(drop=True)
    )

    top_rows = qualified.head(args.top_n)
    best = top_rows.iloc[0].to_dict() if not top_rows.empty else None
    _write_markdown(metric_frame.sort_values("selection_score", ascending=False), output_dir, args.top_n)

    payload = {
        "created_at": pd.Timestamp.now().isoformat(),
        "grid": {
            "dd252": list(dd252_values),
            "dd120": list(dd120_values),
            "drop5": list(drop5_values),
            "drop10": list(drop10_values),
        },
        "total_tested": int(len(metric_frame)),
        "min_signals": args.min_signals,
        "constraints": {
            "development_trades_min": 40,
            "iteration_trades_min": 20,
            "iteration_max_drawdown_min": -0.28,
            "minimum_positive_returns": [
                "development > 0",
                "iteration > 0",
            ],
        },
        "best_recommended": best,
        "top_recommendations": top_rows.to_dict(orient="records"),
    }
    _emit_json(output_dir / "grid_summary.json", payload)
    print("search completed", flush=True)
    if best is not None:
        print(f"best combo: {best['combo']}", flush=True)


if __name__ == "__main__":
    main()
